CREATE DATABASE EMUSSA
USE EMUSSA

CREATE SCHEMA LAD

CREATE TABLE LAD.TBT_MENU_SUP
(
IDD_MENU_SUP INT IDENTITY(1,1) PRIMARY KEY,
TXT_DESCRIPCION VARCHAR(MAX)
);


CREATE TABLE LAD.TBT_IMAGE_CAROU
(
IDD_IMAGE_CAROU INT IDENTITY(1,1) PRIMARY KEY,
DES_IMAGE_CAROU VARCHAR(500),
URL_IMAGE VARCHAR(500),
NUM_ORDEN INT
);

CREATE TABLE LAD.TBT_SUB_SELEC1
(
IDD_SUB_SELEC1 INT IDENTITY(1,1) PRIMARY KEY,
NOM_TITUL VARCHAR(100),
PARRAF_UNO VARCHAR(500),
PARRAF_DOS VARCHAR(500),
URL_IMAGE_1 VARCHAR(500),
URL_IMAGE_2 VARCHAR(500),
DES_IMAGE_1 VARCHAR(500),
DES_IMAGE_2 VARCHAR(500)
);

CREATE TABLE LAD.TBT_PILARES
(
IDD_PILAR INT IDENTITY(1,1) PRIMARY KEY,
URL_PILAR1 VARCHAR(500),
URL_PILAR2 VARCHAR(500),
URL_PILAR3 VARCHAR(500),
URL_PILAR4 VARCHAR(500),
URL_PILAR5 VARCHAR(500),
DES_PILAR1 VARCHAR(500),
DES_PILAR2 VARCHAR(500),
DES_PILAR3 VARCHAR(500),
DES_PILAR4 VARCHAR(500),
DES_PILAR5 VARCHAR(500),
);

CREATE TABLE LAD.TBT_SUB_SELEC2
(
IDD_SUB_SELEC2 INT IDENTITY(1,1) PRIMARY KEY,
NOM_TITUL VARCHAR(100),
PARRAF_UNO VARCHAR(500),
PARRAF_DOS VARCHAR(500),
URL_IMAGE_1 VARCHAR(500),
DES_IMAGE_1 VARCHAR(500)
);

CREATE TABLE LAD.TBT_IMAGE_BLOG
(
IDD_IMAGE_BLOG INT IDENTITY(1,1) PRIMARY KEY,
DES_IMAGE_BLOG VARCHAR(500),
URL_IMAGE VARCHAR(500),
NUM_ORDEN INT
);

CREATE TABLE LAD.TBT_CARDS_EVENT
(
IDD_CARDS_EVENT INT IDENTITY(1,1) PRIMARY KEY,
DES_CARDS_EVENT VARCHAR(500),
URL_IMAGE VARCHAR(500),
NUM_ORDEN INT,
DES_TITUL_CARD VARCHAR(500)
);

CREATE TABLE LAD.TBT_CORREO
(
IDD_CORREO INT IDENTITY(1,1) PRIMARY KEY,
DES_CORREO VARCHAR(500)
);

CREATE TABLE LAD.TBD_TELEF
(
IDD_TELEF INT IDENTITY(1,1) PRIMARY KEY,
DES_TELEF VARCHAR(20)
);

select * from LAD.TBT_MENU_SUP
select * from LAD.TBT_IMAGE_CAROU
select * from LAD.TBT_SUB_SELEC1
select * from LAD.TBT_PILARES
select * from LAD.TBT_SUB_SELEC2
select * from LAD.TBT_IMAGE_BLOG
select * from LAD.TBT_CARDS_EVENT
select * from LAD.TBT_CORREO
select * from LAD.TBD_TELEF